export const mockActivities = [
  {
    id: 1,
    user: 'João Silva',
    action: 'moveu o Negócio',
    target: 'Implantação ERP',
    time: 'Há 5 min',
  },
  {
    id: 2,
    user: 'Maria Oliveira',
    action: 'adicionou um novo Contato',
    target: 'Carlos Mendes',
    time: 'Há 30 min',
  },
  {
    id: 3,
    user: 'Você',
    action: 'concluiu a tarefa',
    target: 'Ligar para a TechCorp',
    time: 'Há 2 horas',
  },
  {
    id: 4,
    user: 'Ana Souza',
    action: 'fechou o Negócio',
    target: 'Consultoria Financeira',
    time: 'Ontem',
  },
]

export const mockChartData = [
  { name: 'Jan', atual: 4000, previsto: 4500 },
  { name: 'Fev', atual: 5500, previsto: 5000 },
  { name: 'Mar', atual: 3000, previsto: 4800 },
  { name: 'Abr', atual: 6500, previsto: 6000 },
  { name: 'Mai', atual: 7000, previsto: 6500 },
  { name: 'Jun', atual: 8500, previsto: 7200 },
]

export const mockContacts = [
  {
    id: '1',
    nome: 'Carlos Mendes',
    empresa: 'TechCorp S.A',
    email: 'carlos@techcorp.com',
    telefone: '(11) 98765-4321',
    status: 'Cliente',
    ultimoContato: '2023-10-25',
  },
  {
    id: '2',
    nome: 'Fernanda Lima',
    empresa: 'Inova Design',
    email: 'fernanda@inova.com',
    telefone: '(21) 97654-3210',
    status: 'Lead',
    ultimoContato: '2023-10-26',
  },
  {
    id: '3',
    nome: 'Roberto Alves',
    empresa: 'Global Logistics',
    email: 'roberto@global.com',
    telefone: '(31) 99999-8888',
    status: 'Prospect',
    ultimoContato: '2023-10-20',
  },
  {
    id: '4',
    nome: 'Juliana Costa',
    empresa: 'Smart Solutions',
    email: 'juliana@smart.com',
    telefone: '(41) 98888-7777',
    status: 'Cliente',
    ultimoContato: '2023-10-27',
  },
  {
    id: '5',
    nome: 'Eduardo Gomes',
    empresa: 'Agro Brasil',
    email: 'eduardo@agro.com',
    telefone: '(62) 97777-6666',
    status: 'Lead',
    ultimoContato: '2023-10-21',
  },
]

export type DealStatus = 'Prospecção' | 'Qualificação' | 'Proposta' | 'Negociação' | 'Fechado'

export const mockDeals = [
  {
    id: 'd1',
    name: 'Implantação ERP',
    company: 'TechCorp S.A',
    value: 25000,
    status: 'Proposta' as DealStatus,
    owner: 'João',
    avatar: '1',
    stagnant: false,
  },
  {
    id: 'd2',
    name: 'Redesign de Marca',
    company: 'Inova Design',
    value: 8500,
    status: 'Qualificação' as DealStatus,
    owner: 'Maria',
    avatar: '2',
    stagnant: true,
  },
  {
    id: 'd3',
    name: 'Logística Avançada',
    company: 'Global Logistics',
    value: 45000,
    status: 'Negociação' as DealStatus,
    owner: 'Ana',
    avatar: '3',
    stagnant: false,
  },
  {
    id: 'd4',
    name: 'Consultoria Financeira',
    company: 'Smart Solutions',
    value: 12000,
    status: 'Fechado' as DealStatus,
    owner: 'João',
    avatar: '1',
    stagnant: false,
  },
  {
    id: 'd5',
    name: 'Software Agrícola',
    company: 'Agro Brasil',
    value: 32000,
    status: 'Prospecção' as DealStatus,
    owner: 'Você',
    avatar: '4',
    stagnant: false,
  },
  {
    id: 'd6',
    name: 'Treinamento de Equipe',
    company: 'TechCorp S.A',
    value: 5000,
    status: 'Prospecção' as DealStatus,
    owner: 'Maria',
    avatar: '2',
    stagnant: false,
  },
]

export const mockTasks = [
  {
    id: 't1',
    title: 'Ligar para a TechCorp',
    date: 'Hoje, 14:00',
    priority: 'Alta',
    completed: false,
    owner: 'Você',
  },
  {
    id: 't2',
    title: 'Enviar proposta para Inova Design',
    date: 'Hoje, 16:30',
    priority: 'Média',
    completed: false,
    owner: 'Você',
  },
  {
    id: 't3',
    title: 'Reunião de alinhamento com Global',
    date: 'Amanhã, 10:00',
    priority: 'Alta',
    completed: false,
    owner: 'Equipe',
  },
  {
    id: 't4',
    title: 'Atualizar CRM com novos leads',
    date: 'Amanhã, 15:00',
    priority: 'Baixa',
    completed: true,
    owner: 'Você',
  },
  {
    id: 't5',
    title: 'Apresentação final Smart Solutions',
    date: '29/10/2023',
    priority: 'Alta',
    completed: false,
    owner: 'Equipe',
  },
]
